/* PitchIQ closed mobile demo data — July 18, 2025 Pro snapshot (offline). */
(function (global) {
  "use strict";

function demoGame(overrides) {
  return {
    event_key: "",
    pitcher: "",
    pitcher_team: "",
    opponent: "",
    date: "07/18/2025",
    game_date_raw: "2025-07-18",
    sort_datetime: "2025-07-18T19:05:00-04:00",
    start_time: "2025-07-18T19:05:00-04:00",
    time: "7:05 PM",
    game_status: "Scheduled",
    venue: "",
    home_or_away: "",
    plate_umpire: "Pending",
    dk_line: 5.5,
    dk_over_payout: "-115",
    dk_under_payout: "-105",
    dk_bet: "PASS",
    dk_confidence: "Low",
    dk_edge: 0,
    dk_over_probability: 0.5,
    dk_under_probability: 0.5,
    fd_line: 5.5,
    fd_over_payout: "-110",
    fd_under_payout: "-110",
    fd_bet: "PASS",
    fd_confidence: "Low",
    fd_edge: 0,
    fd_over_probability: 0.5,
    fd_under_probability: 0.5,
    projected_strikeouts: 5.5,
    ensemble_prediction: 5.5,
    poisson_prediction: 5.4,
    linear_prediction: 5.6,
    nonlinear_prediction: 5.5,
    adjusted_EK_full: 5.5,
    adjusted_EK_hand: 5.5,
    volatility_label: "Medium",
    volatility_score: 0.5,
    notes: "",
    upcoming_notes: [],
    ...overrides
  };
}

  const DEMO_UPCOMING_GAMES = [
  {
    "event_key": "demo-20250718-nym-bos",
    "pitcher": "Caleb Moreno",
    "pitcher_team": "New York Mets",
    "opponent": "Boston Red Sox",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T19:10:00-04:00",
    "start_time": "2025-07-18T19:10:00-04:00",
    "time": "7:10 PM",
    "game_status": "Scheduled",
    "venue": "Citi Field",
    "home_or_away": "Home",
    "plate_umpire": "Ryan Blakely",
    "dk_line": 5.5,
    "dk_over_payout": "-108",
    "dk_under_payout": "-112",
    "dk_bet": "OVER",
    "dk_confidence": "High",
    "dk_edge": 1.18,
    "dk_over_probability": 0.61,
    "dk_under_probability": 0.39,
    "fd_line": 6.5,
    "fd_over_payout": "+116",
    "fd_under_payout": "-142",
    "fd_bet": "PASS",
    "fd_confidence": "Low",
    "fd_edge": 0.18,
    "fd_over_probability": 0.49,
    "fd_under_probability": 0.51,
    "projected_strikeouts": 6.68,
    "ensemble_prediction": 6.54,
    "poisson_prediction": 6.72,
    "linear_prediction": 6.41,
    "nonlinear_prediction": 6.89,
    "adjusted_EK_full": 6.68,
    "adjusted_EK_hand": 6.57,
    "volatility_label": "Low",
    "volatility_score": 0.27,
    "notes": "+DK O/U Line",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better over line at 5.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 1.18 Ks above the <strong>DraftKings</strong> line, pointing toward the over."
      },
      {
        "impact": "neutral",
        "title": "Low Volatility",
        "body": "The model inputs are tightly clustered, so this projection is cleaner than usual."
      },
      {
        "impact": "up",
        "title": "Umpire Context",
        "body": "<strong>Ryan Blakely</strong> has historically created a higher strikeout environment."
      }
    ]
  },
  {
    "event_key": "demo-20250718-sea-tex",
    "pitcher": "Derek Walsh",
    "pitcher_team": "Seattle Mariners",
    "opponent": "Texas Rangers",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T20:05:00-04:00",
    "start_time": "2025-07-18T20:05:00-04:00",
    "time": "8:05 PM",
    "game_status": "Scheduled",
    "venue": "Globe Life Field",
    "home_or_away": "Away",
    "plate_umpire": "Mason Cole",
    "dk_line": 6.5,
    "dk_over_payout": "+102",
    "dk_under_payout": "-122",
    "dk_bet": "UNDER",
    "dk_confidence": "Medium",
    "dk_edge": 0.74,
    "dk_over_probability": 0.42,
    "dk_under_probability": 0.58,
    "fd_line": 6.5,
    "fd_over_payout": "+104",
    "fd_under_payout": "-128",
    "fd_bet": "UNDER",
    "fd_confidence": "Medium",
    "fd_edge": 0.86,
    "fd_over_probability": 0.41,
    "fd_under_probability": 0.59,
    "projected_strikeouts": 5.76,
    "ensemble_prediction": 5.91,
    "poisson_prediction": 5.58,
    "linear_prediction": 5.82,
    "nonlinear_prediction": 5.72,
    "adjusted_EK_full": 5.76,
    "adjusted_EK_hand": 5.88,
    "volatility_label": "Medium",
    "volatility_score": 0.51,
    "notes": "No Major Flags",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 0.74 Ks below the <strong>DraftKings</strong> line, pointing toward the under."
      },
      {
        "impact": "neutral",
        "title": "Plus Money",
        "body": "The recommended under side on <strong>DraftKings</strong> is available at +102."
      },
      {
        "impact": "down",
        "title": "Opponent Handedness",
        "body": "<strong>Texas Rangers</strong> have allowed fewer pitcher strikeouts against right-handed starters."
      },
      {
        "impact": "neutral",
        "title": "Home/Away Split",
        "body": "<strong>Walsh</strong> has been worse in away starts."
      }
    ]
  },
  {
    "event_key": "demo-20250718-atl-phi",
    "pitcher": "Jonah Price",
    "pitcher_team": "Atlanta Braves",
    "opponent": "Philadelphia Phillies",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T18:40:00-04:00",
    "start_time": "2025-07-18T18:40:00-04:00",
    "time": "6:40 PM",
    "game_status": "Scheduled",
    "venue": "Citizens Bank Park",
    "home_or_away": "Away",
    "plate_umpire": "Pending",
    "dk_line": 4.5,
    "dk_over_payout": "-130",
    "dk_under_payout": "+106",
    "dk_bet": "OVER",
    "dk_confidence": "Medium",
    "dk_edge": 0.92,
    "dk_over_probability": 0.6,
    "dk_under_probability": 0.4,
    "fd_line": 5.5,
    "fd_over_payout": "+128",
    "fd_under_payout": "-158",
    "fd_bet": "PASS",
    "fd_confidence": "Low",
    "fd_edge": -0.08,
    "fd_over_probability": 0.46,
    "fd_under_probability": 0.54,
    "projected_strikeouts": 5.42,
    "ensemble_prediction": 5.39,
    "poisson_prediction": 5.21,
    "linear_prediction": 5.64,
    "nonlinear_prediction": 5.44,
    "adjusted_EK_full": 5.42,
    "adjusted_EK_hand": 5.31,
    "volatility_label": "High",
    "volatility_score": 0.76,
    "notes": "+DK O/U Line, Umpire Pending",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better over line at 4.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 0.92 Ks above the <strong>DraftKings</strong> line, pointing toward the over."
      },
      {
        "impact": "neutral",
        "title": "High Volatility",
        "body": "The model inputs are spread out (0.76), so treat this recommendation with more caution."
      },
      {
        "impact": "neutral",
        "title": "Umpire Pending",
        "body": "The home plate umpire is not confirmed yet, so this projection is not using an umpire-specific adjustment."
      }
    ]
  },
  {
    "event_key": "demo-20250718-lad-sd",
    "pitcher": "Marco Silva",
    "pitcher_team": "Los Angeles Dodgers",
    "opponent": "San Diego Padres",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T21:40:00-04:00",
    "start_time": "2025-07-18T21:40:00-04:00",
    "time": "9:40 PM",
    "game_status": "Scheduled",
    "venue": "Petco Park",
    "home_or_away": "Away",
    "plate_umpire": "Elijah Trent",
    "dk_line": 7.5,
    "dk_over_payout": "+118",
    "dk_under_payout": "-144",
    "dk_bet": "UNDER",
    "dk_confidence": "Medium",
    "dk_edge": 0.63,
    "dk_over_probability": 0.43,
    "dk_under_probability": 0.57,
    "fd_line": 6.5,
    "fd_over_payout": "-104",
    "fd_under_payout": "-116",
    "fd_bet": "PASS",
    "fd_confidence": "Low",
    "fd_edge": -0.37,
    "fd_over_probability": 0.47,
    "fd_under_probability": 0.53,
    "projected_strikeouts": 6.87,
    "ensemble_prediction": 6.93,
    "poisson_prediction": 6.71,
    "linear_prediction": 7.04,
    "nonlinear_prediction": 6.81,
    "adjusted_EK_full": 6.87,
    "adjusted_EK_hand": 6.92,
    "volatility_label": "Medium",
    "volatility_score": 0.48,
    "notes": "+DK O/U Line",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better under line at 7.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 0.63 Ks below the <strong>DraftKings</strong> line, pointing toward the under."
      },
      {
        "impact": "down",
        "title": "Park Split",
        "body": "<strong>Petco Park</strong> has led to fewer pitcher strikeouts for right-handed starters."
      },
      {
        "impact": "neutral",
        "title": "Extended Rest",
        "body": "This pitcher is coming in on extra rest."
      }
    ]
  }
];

  const DEMO_LIVE_GAMES = [
  {
    "event_key": "demo-20250718-chc-mil",
    "pitcher": "Nolan Pierce",
    "pitcher_team": "Chicago Cubs",
    "opponent": "Milwaukee Brewers",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T14:20:00-04:00",
    "start_time": "2025-07-18T14:20:00-04:00",
    "time": "2:20 PM",
    "game_status": "Top 4th",
    "venue": "Wrigley Field",
    "home_or_away": "Home",
    "plate_umpire": "Grant Hill",
    "dk_line": 5.5,
    "dk_over_payout": "-108",
    "dk_under_payout": "-112",
    "dk_bet": "OVER",
    "dk_confidence": "Medium",
    "dk_edge": 0.81,
    "dk_over_probability": 0.5,
    "dk_under_probability": 0.5,
    "fd_line": 5.5,
    "fd_over_payout": "-105",
    "fd_under_payout": "-115",
    "fd_bet": "OVER",
    "fd_confidence": "Medium",
    "fd_edge": 0.68,
    "fd_over_probability": 0.5,
    "fd_under_probability": 0.5,
    "projected_strikeouts": 6.31,
    "ensemble_prediction": 5.5,
    "poisson_prediction": 5.4,
    "linear_prediction": 5.6,
    "nonlinear_prediction": 5.5,
    "adjusted_EK_full": 5.5,
    "adjusted_EK_hand": 5.5,
    "volatility_label": "Medium",
    "volatility_score": 0.43,
    "notes": "",
    "upcoming_notes": [],
    "live_strikeouts": 3,
    "live_pitch_count": 58,
    "starter_status": "Pitching",
    "game_inning": "Top 4"
  }
];

  const DEMO_HISTORICAL_GAMES = [
  {
    "event_key": "demo-20250718-nym-bos",
    "pitcher": "Caleb Moreno",
    "pitcher_team": "New York Mets",
    "opponent": "Pittsburgh Pirates",
    "date": "07/11/2025",
    "game_date_raw": "2025-07-11",
    "sort_datetime": "2025-07-11T19:10:00-04:00",
    "start_time": "2025-07-18T19:10:00-04:00",
    "time": "7:10 PM",
    "game_status": "Scheduled",
    "venue": "Citi Field",
    "home_or_away": "Home",
    "plate_umpire": "Ryan Blakely",
    "dk_line": 5.5,
    "dk_over_payout": "-108",
    "dk_under_payout": "-112",
    "dk_bet": "OVER",
    "dk_confidence": "High",
    "dk_edge": 1.18,
    "dk_over_probability": 0.61,
    "dk_under_probability": 0.39,
    "fd_line": 6.5,
    "fd_over_payout": "+116",
    "fd_under_payout": "-142",
    "fd_bet": "OVER",
    "fd_confidence": "Low",
    "fd_edge": 0.18,
    "fd_over_probability": 0.49,
    "fd_under_probability": 0.51,
    "projected_strikeouts": 6.68,
    "ensemble_prediction": 6.54,
    "poisson_prediction": 6.72,
    "linear_prediction": 6.41,
    "nonlinear_prediction": 6.89,
    "adjusted_EK_full": 6.68,
    "adjusted_EK_hand": 6.57,
    "volatility_label": "Low",
    "volatility_score": 0.27,
    "notes": "+DK O/U Line",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better over line at 5.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 1.18 Ks above the <strong>DraftKings</strong> line, pointing toward the over."
      },
      {
        "impact": "neutral",
        "title": "Low Volatility",
        "body": "The model inputs are tightly clustered, so this projection is cleaner than usual."
      },
      {
        "impact": "up",
        "title": "Umpire Context",
        "body": "<strong>Ryan Blakely</strong> has historically created a higher strikeout environment."
      }
    ],
    "actual_k": 8
  },
  {
    "event_key": "demo-20250718-sea-tex",
    "pitcher": "Derek Walsh",
    "pitcher_team": "Seattle Mariners",
    "opponent": "Houston Astros",
    "date": "07/12/2025",
    "game_date_raw": "2025-07-12",
    "sort_datetime": "2025-07-12T20:05:00-04:00",
    "start_time": "2025-07-18T20:05:00-04:00",
    "time": "8:05 PM",
    "game_status": "Scheduled",
    "venue": "Globe Life Field",
    "home_or_away": "Away",
    "plate_umpire": "Mason Cole",
    "dk_line": 6.5,
    "dk_over_payout": "+102",
    "dk_under_payout": "-122",
    "dk_bet": "UNDER",
    "dk_confidence": "Medium",
    "dk_edge": 0.74,
    "dk_over_probability": 0.42,
    "dk_under_probability": 0.58,
    "fd_line": 6.5,
    "fd_over_payout": "+104",
    "fd_under_payout": "-128",
    "fd_bet": "UNDER",
    "fd_confidence": "Medium",
    "fd_edge": 0.86,
    "fd_over_probability": 0.41,
    "fd_under_probability": 0.59,
    "projected_strikeouts": 5.76,
    "ensemble_prediction": 5.91,
    "poisson_prediction": 5.58,
    "linear_prediction": 5.82,
    "nonlinear_prediction": 5.72,
    "adjusted_EK_full": 5.76,
    "adjusted_EK_hand": 5.88,
    "volatility_label": "Medium",
    "volatility_score": 0.51,
    "notes": "No Major Flags",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 0.74 Ks below the <strong>DraftKings</strong> line, pointing toward the under."
      },
      {
        "impact": "neutral",
        "title": "Plus Money",
        "body": "The recommended under side on <strong>DraftKings</strong> is available at +102."
      },
      {
        "impact": "down",
        "title": "Opponent Handedness",
        "body": "<strong>Texas Rangers</strong> have allowed fewer pitcher strikeouts against right-handed starters."
      },
      {
        "impact": "neutral",
        "title": "Home/Away Split",
        "body": "<strong>Walsh</strong> has been worse in away starts."
      }
    ],
    "actual_k": 7
  },
  {
    "event_key": "demo-20250718-atl-phi",
    "pitcher": "Jonah Price",
    "pitcher_team": "Atlanta Braves",
    "opponent": "Miami Marlins",
    "date": "07/13/2025",
    "game_date_raw": "2025-07-13",
    "sort_datetime": "2025-07-13T13:35:00-04:00",
    "start_time": "2025-07-18T18:40:00-04:00",
    "time": "6:40 PM",
    "game_status": "Scheduled",
    "venue": "Citizens Bank Park",
    "home_or_away": "Away",
    "plate_umpire": "Victor Hale",
    "dk_line": 4.5,
    "dk_over_payout": "-130",
    "dk_under_payout": "+106",
    "dk_bet": "OVER",
    "dk_confidence": "Medium",
    "dk_edge": 0.92,
    "dk_over_probability": 0.6,
    "dk_under_probability": 0.4,
    "fd_line": 5.5,
    "fd_over_payout": "+128",
    "fd_under_payout": "-158",
    "fd_bet": "UNDER",
    "fd_confidence": "Low",
    "fd_edge": -0.08,
    "fd_over_probability": 0.46,
    "fd_under_probability": 0.54,
    "projected_strikeouts": 5.42,
    "ensemble_prediction": 5.39,
    "poisson_prediction": 5.21,
    "linear_prediction": 5.64,
    "nonlinear_prediction": 5.44,
    "adjusted_EK_full": 5.42,
    "adjusted_EK_hand": 5.31,
    "volatility_label": "High",
    "volatility_score": 0.76,
    "notes": "+DK O/U Line",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better over line at 4.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 0.92 Ks above the <strong>DraftKings</strong> line, pointing toward the over."
      },
      {
        "impact": "neutral",
        "title": "High Volatility",
        "body": "The model inputs are spread out (0.76), so treat this recommendation with more caution."
      },
      {
        "impact": "neutral",
        "title": "Umpire Pending",
        "body": "The home plate umpire is not confirmed yet, so this projection is not using an umpire-specific adjustment."
      }
    ],
    "actual_k": 4
  },
  {
    "event_key": "demo-20250718-lad-sd",
    "pitcher": "Marco Silva",
    "pitcher_team": "Los Angeles Dodgers",
    "opponent": "Arizona Diamondbacks",
    "date": "07/09/2025",
    "game_date_raw": "2025-07-09",
    "sort_datetime": "2025-07-09T21:40:00-04:00",
    "start_time": "2025-07-18T21:40:00-04:00",
    "time": "9:40 PM",
    "game_status": "Scheduled",
    "venue": "Petco Park",
    "home_or_away": "Away",
    "plate_umpire": "Elijah Trent",
    "dk_line": 7.5,
    "dk_over_payout": "+118",
    "dk_under_payout": "-144",
    "dk_bet": "UNDER",
    "dk_confidence": "Medium",
    "dk_edge": 0.63,
    "dk_over_probability": 0.43,
    "dk_under_probability": 0.57,
    "fd_line": 6.5,
    "fd_over_payout": "-104",
    "fd_under_payout": "-116",
    "fd_bet": "PASS",
    "fd_confidence": "Low",
    "fd_edge": -0.37,
    "fd_over_probability": 0.47,
    "fd_under_probability": 0.53,
    "projected_strikeouts": 6.87,
    "ensemble_prediction": 6.93,
    "poisson_prediction": 6.71,
    "linear_prediction": 7.04,
    "nonlinear_prediction": 6.81,
    "adjusted_EK_full": 6.87,
    "adjusted_EK_hand": 6.92,
    "volatility_label": "Medium",
    "volatility_score": 0.48,
    "notes": "+DK O/U Line",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better under line at 7.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 0.63 Ks below the <strong>DraftKings</strong> line, pointing toward the under."
      },
      {
        "impact": "down",
        "title": "Park Split",
        "body": "<strong>Petco Park</strong> has led to fewer pitcher strikeouts for right-handed starters."
      },
      {
        "impact": "neutral",
        "title": "Extended Rest",
        "body": "This pitcher is coming in on extra rest."
      }
    ],
    "actual_k": 6
  },
  {
    "event_key": "demo-20250718-chc-mil",
    "pitcher": "Nolan Pierce",
    "pitcher_team": "Chicago Cubs",
    "opponent": "Cincinnati Reds",
    "date": "07/10/2025",
    "game_date_raw": "2025-07-10",
    "sort_datetime": "2025-07-10T14:20:00-04:00",
    "start_time": "2025-07-18T14:20:00-04:00",
    "time": "2:20 PM",
    "game_status": "Final",
    "venue": "Wrigley Field",
    "home_or_away": "Home",
    "plate_umpire": "Grant Hill",
    "dk_line": 5.5,
    "dk_over_payout": "-108",
    "dk_under_payout": "-112",
    "dk_bet": "OVER",
    "dk_confidence": "Medium",
    "dk_edge": 0.81,
    "dk_over_probability": 0.5,
    "dk_under_probability": 0.5,
    "fd_line": 5.5,
    "fd_over_payout": "-105",
    "fd_under_payout": "-115",
    "fd_bet": "OVER",
    "fd_confidence": "Medium",
    "fd_edge": 0.68,
    "fd_over_probability": 0.5,
    "fd_under_probability": 0.5,
    "projected_strikeouts": 6.31,
    "ensemble_prediction": 5.5,
    "poisson_prediction": 5.4,
    "linear_prediction": 5.6,
    "nonlinear_prediction": 5.5,
    "adjusted_EK_full": 5.5,
    "adjusted_EK_hand": 5.5,
    "volatility_label": "Medium",
    "volatility_score": 0.43,
    "notes": "No Major Flags",
    "upcoming_notes": [],
    "actual_k": 6
  }
];

  const DEMO_MY_CARDS = [
  {
    "event_key": "demo-20250718-nym-bos",
    "pitcher": "Caleb Moreno",
    "pitcher_team": "New York Mets",
    "opponent": "Boston Red Sox",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T19:10:00-04:00",
    "start_time": "2025-07-18T19:10:00-04:00",
    "time": "7:10 PM",
    "game_status": "Scheduled",
    "venue": "Citi Field",
    "home_or_away": "Home",
    "plate_umpire": "Ryan Blakely",
    "dk_line": 5.5,
    "dk_over_payout": "-108",
    "dk_under_payout": "-112",
    "dk_bet": "OVER",
    "dk_confidence": "High",
    "dk_edge": 1.18,
    "dk_over_probability": 0.61,
    "dk_under_probability": 0.39,
    "fd_line": 6.5,
    "fd_over_payout": "+116",
    "fd_under_payout": "-142",
    "fd_bet": "PASS",
    "fd_confidence": "Low",
    "fd_edge": 0.18,
    "fd_over_probability": 0.49,
    "fd_under_probability": 0.51,
    "projected_strikeouts": 6.68,
    "ensemble_prediction": 6.54,
    "poisson_prediction": 6.72,
    "linear_prediction": 6.41,
    "nonlinear_prediction": 6.89,
    "adjusted_EK_full": 6.68,
    "adjusted_EK_hand": 6.57,
    "volatility_label": "Low",
    "volatility_score": 0.27,
    "notes": "+DK O/U Line",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better over line at 5.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 1.18 Ks above the <strong>DraftKings</strong> line, pointing toward the over."
      },
      {
        "impact": "neutral",
        "title": "Low Volatility",
        "body": "The model inputs are tightly clustered, so this projection is cleaner than usual."
      },
      {
        "impact": "up",
        "title": "Umpire Context",
        "body": "<strong>Ryan Blakely</strong> has historically created a higher strikeout environment."
      }
    ],
    "_saved_card_id": "demo-card-1",
    "_saved_at": "2025-07-18T09:22:00-04:00"
  },
  {
    "event_key": "demo-20250718-atl-phi",
    "pitcher": "Jonah Price",
    "pitcher_team": "Atlanta Braves",
    "opponent": "Philadelphia Phillies",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T18:40:00-04:00",
    "start_time": "2025-07-18T18:40:00-04:00",
    "time": "6:40 PM",
    "game_status": "Scheduled",
    "venue": "Citizens Bank Park",
    "home_or_away": "Away",
    "plate_umpire": "Pending",
    "dk_line": 4.5,
    "dk_over_payout": "-130",
    "dk_under_payout": "+106",
    "dk_bet": "OVER",
    "dk_confidence": "Medium",
    "dk_edge": 0.92,
    "dk_over_probability": 0.6,
    "dk_under_probability": 0.4,
    "fd_line": 5.5,
    "fd_over_payout": "+128",
    "fd_under_payout": "-158",
    "fd_bet": "PASS",
    "fd_confidence": "Low",
    "fd_edge": -0.08,
    "fd_over_probability": 0.46,
    "fd_under_probability": 0.54,
    "projected_strikeouts": 5.42,
    "ensemble_prediction": 5.39,
    "poisson_prediction": 5.21,
    "linear_prediction": 5.64,
    "nonlinear_prediction": 5.44,
    "adjusted_EK_full": 5.42,
    "adjusted_EK_hand": 5.31,
    "volatility_label": "High",
    "volatility_score": 0.76,
    "notes": "+DK O/U Line, Umpire Pending",
    "upcoming_notes": [
      {
        "impact": "neutral",
        "title": "Line Value",
        "body": "<strong>DraftKings</strong> is offering the better over line at 4.5."
      },
      {
        "impact": "neutral",
        "title": "Projection vs Line",
        "body": "The projection is 0.92 Ks above the <strong>DraftKings</strong> line, pointing toward the over."
      },
      {
        "impact": "neutral",
        "title": "High Volatility",
        "body": "The model inputs are spread out (0.76), so treat this recommendation with more caution."
      },
      {
        "impact": "neutral",
        "title": "Umpire Pending",
        "body": "The home plate umpire is not confirmed yet, so this projection is not using an umpire-specific adjustment."
      }
    ],
    "_saved_card_id": "demo-card-2",
    "_saved_at": "2025-07-18T09:35:00-04:00"
  },
  {
    "event_key": "demo-20250718-chc-mil",
    "pitcher": "Nolan Pierce",
    "pitcher_team": "Chicago Cubs",
    "opponent": "Milwaukee Brewers",
    "date": "07/18/2025",
    "game_date_raw": "2025-07-18",
    "sort_datetime": "2025-07-18T14:20:00-04:00",
    "start_time": "2025-07-18T14:20:00-04:00",
    "time": "2:20 PM",
    "game_status": "Top 4th",
    "venue": "Wrigley Field",
    "home_or_away": "Home",
    "plate_umpire": "Grant Hill",
    "dk_line": 5.5,
    "dk_over_payout": "-108",
    "dk_under_payout": "-112",
    "dk_bet": "OVER",
    "dk_confidence": "Medium",
    "dk_edge": 0.81,
    "dk_over_probability": 0.5,
    "dk_under_probability": 0.5,
    "fd_line": 5.5,
    "fd_over_payout": "-105",
    "fd_under_payout": "-115",
    "fd_bet": "OVER",
    "fd_confidence": "Medium",
    "fd_edge": 0.68,
    "fd_over_probability": 0.5,
    "fd_under_probability": 0.5,
    "projected_strikeouts": 6.31,
    "ensemble_prediction": 5.5,
    "poisson_prediction": 5.4,
    "linear_prediction": 5.6,
    "nonlinear_prediction": 5.5,
    "adjusted_EK_full": 5.5,
    "adjusted_EK_hand": 5.5,
    "volatility_label": "Medium",
    "volatility_score": 0.43,
    "notes": "",
    "upcoming_notes": [],
    "live_strikeouts": 3,
    "live_pitch_count": 58,
    "starter_status": "Pitching",
    "game_inning": "Top 4",
    "_saved_card_id": "demo-card-3",
    "_saved_at": "2025-07-18T10:04:00-04:00"
  }
];

  const DEMO_FAVORITE_PITCHERS = [
  "Caleb Moreno",
  "Jonah Price"
];

  const PitchIQDemoData = {
    demoGame,
    DEMO_UPCOMING_GAMES,
    DEMO_LIVE_GAMES,
    DEMO_HISTORICAL_GAMES,
    DEMO_MY_CARDS,
    DEMO_FAVORITE_PITCHERS
  };

  global.demoGame = demoGame;
  global.DEMO_UPCOMING_GAMES = DEMO_UPCOMING_GAMES;
  global.DEMO_LIVE_GAMES = DEMO_LIVE_GAMES;
  global.DEMO_HISTORICAL_GAMES = DEMO_HISTORICAL_GAMES;
  global.DEMO_MY_CARDS = DEMO_MY_CARDS;
  global.DEMO_FAVORITE_PITCHERS = DEMO_FAVORITE_PITCHERS;
  global.PitchIQDemoData = PitchIQDemoData;
})(typeof window !== "undefined" ? window : globalThis);
